### ISSUE TITLE
How to enable culling

### ISSUE THREAD

**Issue by artnas** [AlexisBacot/UnityOcclusionPerTriangleGPU#1]
Hey. I've read your blog post and github readme, but it's not clear to me how to use this for culling in a camera.

I'm on Unity 2021.2.0b15

Or is that not a part of this project?

**Comment by AlexisBacot** [comment]
Hi Artnas, Culling is not part of this project. The scene is rendered very quickly (and cheaply) using a compute shader to know which triangles are visible by the camera. And that's it. BUT you could use this information for culling in a second pass. I have no idea how this compares relatively to other culling techniques, but for a gpu supporting compute shader it should be quite good. It is similar to the HDPR Custom Pass AOV Export feature but limited to Object ID only.
